### ISSUE TITLE
generate_emu_config exception for appid 282800

### ISSUE THREAD

**Issue by otavepto** [otavepto/gbe_fork#191]
reported here: https://cs.rin.ru/forum/viewtopic.php?p=3053239#p3053239

```shell
********* generating info for app id 282800 *********
App name on store: '100% Orange Juice'
output dir: 'output\282800'
downloading app details in: output\282800\info\app_details.json
finding achievements stats...
Unexpected error:
could not convert string to float: 'o'
-----------------------
Traceback (most recent call last):
 
  File "stats_schema_achievement_gen\achievements_gen.py", line 95, in generate_stats_achievements
 
ValueError: invalid literal for int() with base 10: 'o'
 
 
During handling of the above exception, another exception occurred:
 
 
Traceback (most recent call last):
 
  File "generate_emu_config.py", line 1023, in <module>
 
  File "generate_emu_config.py", line 818, in main
 
  File "generate_emu_config.py", line 411, in generate_achievement_stats
 
  File "stats_schema_achievement_gen\achievements_gen.py", line 97, in generate_stats_achievements
 
ValueError: could not convert string to float: 'o'
```

**Comment by Detanup01** [comment]
indeed their achi schema has a 'o' instead of '0' :DD
fix will be depoloayed

**Comment by Detanup01** [comment]
no it still having it.
