### ISSUE TITLE
Getting `SSL: CERTIFICATE_VERIFY_FAILED` in generate_emu_config only when using steam account

### ISSUE THREAD

**Issue by elyashivhazan** [otavepto/gbe_fork#222]
Im getting this error on Bazzite v40.20240611.0 and on Arch linux

`> generate_emu_config 544330`
[Output on pastebin.com](https://pastebin.com/AuGcYVZQ)

**Comment by Detanup01** [comment]
python -m pip list
python --version
and show the result

**Comment by Detanup01** [comment]
My Result:

[pip_python_result.txt](https://github.com/user-attachments/files/15840071/pip_python_result.txt)

**Comment by elyashivhazan** [comment]
> python -m pip list python --version and show the result

did it helped u? can u reproduce this issue (do u have linux installed)?

**Comment by Detanup01** [comment]
try updateing pip and urllib3 package to something like 2.2.1

**Comment by elyashivhazan** [comment]
I created a venv with ur pkgs
```sh
python -m venv .gse
. .gse/bin/activate
for p in $(sed '1,3d' ~/files/downloads/pip_python_result.txt | awk '{print $1}'); do pip install $p; done
```

Still:
```
> generate_emu_config -imgs -clean 892970
generate_emu_config -imgs -clean 892970
********* generating info for app id 892970 *********
App name on store: 'Valheim'
cleaning output folder before generating any data
output dir: 'output/892970'
downloading app details in: output/892970/info/app_details.json
finding achievements stats...
2442408209 controller_mobile_touch
Unexpected error:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
-----------------------
Traceback (most recent call last):

  File "urllib/request.py", line 1348, in do_open

  File "http/client.py", line 1283, in request

  File "http/client.py", line 1329, in _send_request

  File "http/client.py", line 1278, in endheaders

  File "http/client.py", line 1038, in _send_output

  File "http/client.py", line 976, in send

  File "http/client.py", line 1455, in connect

  File "ssl.py", line 513, in wrap_socket

  File "ssl.py", line 1100, in _create

  File "ssl.py", line 1371, in do_handshake

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "generate_emu_config.py", line 1023, in <module>

  File "generate_emu_config.py", line 924, in main

  File "generate_emu_config.py", line 465, in download_published_file

  File "urllib/request.py", line 216, in urlopen

  File "urllib/request.py", line 519, in open

  File "urllib/request.py", line 536, in _open

  File "urllib/request.py", line 496, in _call_chain

  File "urllib/request.py", line 1391, in https_open

  File "urllib/request.py", line 1351, in do_open

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

-----------------------
```

```
> pip freeze
aiohttp==3.9.5
aioquic==1.0.0
aiosignal==1.3.1
anyio==4.4.0
asgiref==3.8.1
async-timeout==4.0.3
attrs==23.2.0
backoff==2.2.1
blinker==1.8.2
botocore==1.34.127
Brotli==1.1.0
CacheControl==0.14.0
cachetools==5.3.3
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==42.0.8
dep-logic==0.2.0
distlib==0.3.8
exceptiongroup==1.2.1
filelock==3.15.1
findpython==0.6.1
Flask==3.0.3
frida==16.3.3
frozenlist==1.4.1
gevent==24.2.1
gevent-eventemitter==2.1
gql==3.5.0
graphql-core==3.2.3
greenlet==3.0.3
h11==0.14.0
h2==4.1.0
hishel==0.0.27
hpack==4.0.0
httpcore==1.0.5
httpx==0.27.0
hyperframe==6.0.1
idna==3.7
importlib_metadata==7.1.0
importlib_resources==6.4.0
iniconfig==2.0.0
installer==0.7.0
itsdangerous==2.2.0
Jinja2==3.1.4
jmespath==1.0.1
kaitaistruct==0.10
ldap3==2.9.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mitmproxy==10.3.1
mitmproxy_rs==0.5.2
msgpack==1.0.8
multidict==6.0.5
outcome==1.3.0.post0
packaging==24.1
passlib==1.7.4
pbs-installer==2024.4.24
pdm==2.15.4
platformdirs==4.2.2
pluggy==1.5.0
protobuf==5.27.0
publicsuffix2==2.20191221
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pycryptodome==3.20.0
pycryptodomex==3.20.0
pydivert==2.1.0
Pygments==2.18.0
pylsqpack==0.3.18
pyOpenSSL==24.1.0
pyparsing==3.1.2
pyperclip==1.8.2
pyproject_hooks==1.1.0
PySocks==1.7.1
pytest==8.2.2
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
PyVirtualDisplay==3.0
requests==2.32.3
requests-toolbelt==1.0.0
resolvelib==1.0.1
rich==13.7.1
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
selenium==4.21.0
service-identity==24.1.0
setuptools==70.0.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
socksio==1.0.0
sortedcontainers==2.4.0
steam==1.4.4
tomli==2.0.1
tomlkit==0.12.5
tornado==6.4
trio==0.25.1
trio-websocket==0.11.1
truststore==0.9.1
typing_extensions==4.12.2
unearth==0.15.4
urllib3==2.2.1
urwid==2.6.14
urwid-mitmproxy==2.1.2.1
uuid==1.30
vdf==3.4
virtualenv==20.26.2
wcwidth==0.2.13
webdriver-manager==4.0.1
websockets==12.0
Werkzeug==3.0.3
wsproto==1.2.0
xvfbwrapper==0.2.9
yarl==1.9.4
zipp==3.19.2
zope.event==5.0
zope.interface==6.4.post2
zstandard==0.22.0
```

**Comment by elyashivhazan** [comment]
```
> pip install --upgrade certifi          
Requirement already satisfied: certifi in /var/home/user/.1/gse/.gse/lib64/python3.12/site-packages (2024.6.2)
```
and i also ran `pip install pip-system-certs` as written in the first link

i have tried on both my systems with a venv and still nothing got solved same error

am i the only one with this error? do u get it as well while trying running this script?

**Comment by elyashivhazan** [comment]
hi, if i understand u right then just to make it clear i didnt freeze any pkgs all of them are on latest on a newly created venv and all the pkgs are from @Detanup01 system ([comment](https://github.com/otavepto/gbe_fork/issues/222#issuecomment-2168254984)).

i cant downgrade easily python because the arch machine is my server and bazzite is immutable so it cant be done but what i can try to do is to run a container but that will be tomorrow.

could u give me more instructions on what and how to use REPL? (do u mean the online python [site](https://replit.com)?)

thanks for the follow up.

**Comment by elyashivhazan** [comment]
ok so the issue is only in the compressed "compiled" release, if using the python script from the git repo `git clone ...` then no ssl issue and the script dose find achievements.

with a new venv on python 3.10.9:
```
> python --version && python -m venv .gse_310 && . .gse_310/bin/activate && pip list && pip install -U urllib3 && pip list
Python 3.10.9
Package    Version
---------- -------
pip        22.3.1
setuptools 65.5.0

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Collecting urllib3
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Installing collected packages: urllib3
Successfully installed urllib3-2.2.1

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Package    Version
---------- -------
pip        22.3.1
setuptools 65.5.0
urllib3    2.2.1

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
```

```
> pip install "steam[client]"
i didnt copy the output
```

```
> pip list                                      
Package             Version
------------------- ---------
cachetools          5.3.3
certifi             2024.6.2
charset-normalizer  3.3.2
gevent              24.2.1
gevent-eventemitter 2.1
greenlet            3.0.3
idna                3.7
pip                 22.3.1
protobuf            3.20.3
pycryptodomex       3.20.0
requests            2.32.3
setuptools          65.5.0
six                 1.16.0
steam               1.4.4
urllib3             2.2.1
vdf                 3.4
zope.event          5.0
zope.interface      6.4.post2

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
```

i think its just need an update for the dependencies.

---

just to make sure but not related
this is the fork struct?
```
> tree steam_settings 
steam_settings
├── achievements.json
├── configs.app.ini
├── depots.txt
├── img
│   ├── cfc27e918907ca28d9a4b77f7f4537cf52b4bfa2.jpg
│   ├── ...
│   └── portal_longjump.jpg
├── stats.txt
├── steam_appid.txt
└── supported_languages.txt

2 directories, 36 files
```

**Comment by elyashivhazan** [comment]
now its working and i didnt needed to create a venv or use an older version of python
thanks for ur help
---

> just to make sure but not related this is the fork struct?
> 
> ```
> > tree steam_settings 
> steam_settings
> ├── achievements.json
> ├── configs.app.ini
> ├── depots.txt
> ├── img
> │   ├── cfc27e918907ca28d9a4b77f7f4537cf52b4bfa2.jpg
> │   ├── ...
> │   └── portal_longjump.jpg
> ├── stats.txt
> ├── steam_appid.txt
> └── supported_languages.txt
> 
> 2 directories, 36 files
> ```
?

**Comment by elyashivhazan** [comment]
> Did you use the built/frozen package from the above link? If so we can create a PR and integrate this upgrade Edit: the directory looks good to me except `portal_longjump.jpg`, images have a hash name usually

yes from the link and its working with `-anon` and logged in so thats good, u can create that pr.

---

about the `img` folder:
this is `achievements.json` well at least the thing that matters for this
```
> grep "icon" achievements.json        
    "icon": "img/portal_getportalguns.jpg",
    "icon_gray": "img/portal_getportalguns_bw.jpg",
    "icon": "img/portal_kill_companioncube.jpg",
    "icon_gray": "img/portal_kill_companioncube_bw.jpg",
    "icon": "img/portal_escape_testchambers.jpg",
    "icon_gray": "img/portal_escape_testchambers_bw.jpg",
    "icon": "img/portal_beat_game.jpg",
    "icon_gray": "img/portal_beat_game_bw.jpg",
    "icon": "img/portal_infinitefall.jpg",
    "icon_gray": "img/portal_infinitefall_bw.jpg",
    "icon": "img/portal_longjump.jpg",
    "icon_gray": "img/portal_longjump_bw.jpg",
    "icon": "img/portal_beat_2advancedmaps.jpg",
    "icon_gray": "img/portal_beat_2advancedmaps_bw.jpg",
    "icon": "img/portal_beat_4advancedmaps.jpg",
    "icon_gray": "img/portal_beat_4advancedmaps_bw.jpg",
    "icon": "img/portal_beat_6advancedmaps.jpg",
    "icon_gray": "img/portal_beat_6advancedmaps_bw.jpg",
    "icon": "img/portal_get_allbronze.jpg",
    "icon_gray": "img/portal_get_allbronze_bw.jpg",
    "icon": "img/portal_get_allsilver.jpg",
    "icon_gray": "img/portal_get_allsilver_bw.jpg",
    "icon": "img/portal_get_allgold.jpg",
    "icon_gray": "img/portal_get_allgold_bw.jpg",
    "icon": "img/portal_detach_all_cameras.jpg",
    "icon_gray": "img/portal_detach_all_cameras_bw.jpg",
    "icon": "img/portal_hit_turret_with_turret.jpg",
    "icon_gray": "img/portal_hit_turret_with_turret_bw.jpg",
    "icon": "img/cfc27e918907ca28d9a4b77f7f4537cf52b4bfa2.jpg",
    "icon_gray": "img/d3a7fbca2549d043955d33cb5eaf30259dcf41ac.jpg",
```
so it dose store only 2 in hash and the rest with a name if u need to know that 🤷‍♂️

---

**but** i have two more issues that related to the frozen pkg but not the ssl error, do u want me to create an issue related to that?

the frozen pkg will not find achievements, logged in or not, and also the frozen pkg is very very very slow compere to running it from the git version (maybe becouse its trying to find achievements but cant?)

**Comment by elyashivhazan** [comment]
400 and i was logged in and im an owner of portal and it did find for portal with the git version

**Comment by elyashivhazan** [comment]
well i was wrong i guess i tried it twice without deleting `-anon` so it dose work sorry for that

**Comment by elyashivhazan** [comment]
but the img name still the sane (with a name) so thats true for both the pkg and the git (same code i guess (: )

**Comment by elyashivhazan** [comment]
so should i close this issue then?
